name: Silverblue ostree to container
on: [workflow_dispatch]

jobs:
  rpm-ostree:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Build and push
      run: >
        env &&
        docker run 
        --privileged 
        --cap-add=ALL
        --ipc=host
        --pid=host
        --tmpfs /tmp
        --tmpfs /run
        --security-opt apparmor=unconfined
        --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
        --volume $(pwd):/tmp/container
        --volume /var/run/docker.sock:/var/run/docker.sock
        --env GITHUB_ACTOR="$GITHUB_ACTOR"
        --env GITHUB_TOKEN="${{secrets.GITHUB_TOKEN}}"
        fedora:latest /tmp/container/build.sh
        # I'm givin' her all she's got, captain!
